import { defineCatalog } from "@json-render/core";
import { schema } from "@json-render/react/schema";
import { z } from "zod";

/**
 * Slide Deck Catalog
 *
 * Components designed for presentation slides.
 * The AI generates a flat tree: Deck > Slides > Content elements.
 * The presenter renders one slide at a time with keyboard navigation.
 */
export const slideCatalog = defineCatalog(schema, {
  components: {
    // Root container
    Deck: {
      props: z.object({
        title: z.string(),
        theme: z
          .enum(["dark", "light", "gradient", "blue", "green"])
          .nullable(),
      }),
      slots: ["default"],
      description:
        "Root container for the slide deck. Children are Slide elements. Always use this as the root element.",
    },

    // Slide container
    Slide: {
      props: z.object({
        layout: z.enum(["center", "left", "split", "top"]).nullable(),
        background: z
          .enum([
            "default",
            "gradient",
            "dark",
            "blue",
            "green",
            "purple",
            "orange",
          ])
          .nullable(),
      }),
      slots: ["default"],
      description:
        "A single slide. Children are content elements rendered inside this slide. layout: 'center' centers content, 'left' aligns left, 'split' divides into two columns (first half of children go left, second half go right), 'top' aligns to top.",
    },

    // Typography
    Title: {
      props: z.object({
        text: z.string(),
        level: z.enum(["h1", "h2", "h3"]).nullable(),
      }),
      description:
        "Large title text. h1 for main slide titles, h2 for section headers, h3 for subtitles.",
    },

    Subtitle: {
      props: z.object({
        text: z.string(),
      }),
      description:
        "Subtitle text shown below a title. Lighter weight, muted color.",
    },

    Text: {
      props: z.object({
        content: z.string(),
        size: z.enum(["sm", "md", "lg"]).nullable(),
        align: z.enum(["left", "center", "right"]).nullable(),
        bold: z.boolean().nullable(),
        muted: z.boolean().nullable(),
      }),
      description: "Body text paragraph for slide content.",
    },

    // Content
    BulletList: {
      props: z.object({
        items: z.array(z.string()),
        ordered: z.boolean().nullable(),
      }),
      description:
        "List of bullet points. Use ordered: true for numbered lists. Each item is a string.",
    },

    CodeBlock: {
      props: z.object({
        code: z.string(),
        language: z.string().nullable(),
      }),
      description:
        "Syntax-highlighted code block. language can be 'javascript', 'typescript', 'python', 'json', 'html', 'css', 'bash', etc.",
    },

    Quote: {
      props: z.object({
        text: z.string(),
        attribution: z.string().nullable(),
      }),
      description:
        "Blockquote with optional attribution for the speaker/source.",
    },

    Image: {
      props: z.object({
        src: z.string(),
        alt: z.string().nullable(),
        caption: z.string().nullable(),
      }),
      description:
        "Image element. Use https://picsum.photos/800/450?random=N for placeholder images (change N for different images). Always provide alt text.",
    },

    // Layout helpers
    TwoColumn: {
      props: z.object({
        ratio: z.enum(["equal", "wide-left", "wide-right"]).nullable(),
      }),
      slots: ["default"],
      description:
        "Two-column layout. First child goes left, second child goes right. ratio controls column widths.",
    },

    Stack: {
      props: z.object({
        direction: z.enum(["horizontal", "vertical"]).nullable(),
        gap: z.enum(["sm", "md", "lg"]).nullable(),
        align: z.enum(["start", "center", "end"]).nullable(),
      }),
      slots: ["default"],
      description: "Flex layout container for arranging child elements.",
    },

    // Decorative
    Badge: {
      props: z.object({
        text: z.string(),
        variant: z
          .enum(["default", "accent", "muted", "success", "warning"])
          .nullable(),
      }),
      description:
        "Small label/tag badge. Good for categories, status indicators, tech stack items.",
    },

    Divider: {
      props: z.object({}),
      description: "Horizontal rule divider between content sections.",
    },

    Spacer: {
      props: z.object({
        size: z.enum(["sm", "md", "lg", "xl"]).nullable(),
      }),
      description: "Vertical spacing between elements.",
    },
  },

  // No actions needed - slides are static content generated by AI
  actions: {},
});

/**
 * Custom rules for the AI when generating slide decks
 */
const customRules = [
  "The root element MUST be a Deck containing Slide children",
  "Each Slide contains content elements (Title, Text, BulletList, etc.)",
  "Create 5-10 slides for a complete presentation",
  "First slide should be a title slide with Title (h1) and Subtitle",
  "Last slide should be a summary or thank you slide",
  "Vary slide layouts: use 'center' for title slides, 'left' for content, 'split' for comparisons",
  "Vary backgrounds across slides for visual interest",
  "Use BulletList for key points, CodeBlock for technical content, Quote for testimonials",
  "Use Badge elements for tags, tech stack items, or categories",
  "For images use https://picsum.photos/800/450?random=N with different N values",
  "Keep text concise - slides should have few words, not paragraphs",
  "Use TwoColumn for side-by-side comparisons or image + text layouts",
];

/**
 * Get the system prompt for AI slide generation
 */
export function getSlidePrompt(): string {
  return slideCatalog.prompt({ customRules });
}
